import UserDataPayload from dp-jwt-verifier-java
ONSdigital/dp-authorisation-java pull request #3
Opened 2022-07-19 16:30 UTC by Marianasilvago

### What
Import UserDataPayload from JWT verifier

### How to review
review code changes

### Who can review
Anyone

2022-07-21 09:00 UTC, cookel2 approved these changes

2022-07-21 09:00 UTC, cookel2 commented on .gitignore
> +.idea
A new line is needed at the end of this file.

2022-07-21 09:01 UTC, cookel2 requested changes
see comment

2022-07-21 09:21 UTC, rafahop commented on src/test/java/com/github/onsdigital/dp/authorisation/permissions/CheckerTest.java
> +                new UserDataPayload("userId", "userEmail", Arrays.asList(new String[]{"admin"})), "users.add", null
We don't really need to create an array when using the `Arrays.asList` and could use var args:
```suggestion
                new UserDataPayload("userId", "userEmail", Arrays.asList("admin")), "users.add", null
```

2022-07-21 15:00 UTC, Marianasilvago commented on .gitignore
> +.idea
New line added

2022-07-21 15:04 UTC, Marianasilvago commented on src/test/java/com/github/onsdigital/dp/authorisation/permissions/CheckerTest.java
> +                new UserDataPayload("userId", "userEmail", Arrays.asList(new String[]{"admin"})), "users.add", null
Fixed redundant array creation for calling varargs method.
Please review it again, thanks for the suggestion.

2022-07-21 16:48 UTC, rafahop approved these changes

2022-07-22 05:58 UTC, cookel2 approved these changes

2022-07-24 16:20 UTC, merged